import type { ModelDefinition } from '../interfaces/model-config.interface.js';

export const MODEL_CATALOG: ModelDefinition[] = [
  {
    id: 'claude-4-sonnet',
    provider: 'anthropic',
    modelName: 'claude-sonnet-4-20250514',
    capabilities: ['coding', 'reasoning', 'planning', 'tool-calling', 'large-context'],
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    supportsStreaming: true,
    supportsToolCalling: true,
  },
  {
    id: 'gpt-4.1',
    provider: 'openai',
    modelName: 'gpt-4.1',
    capabilities: ['coding', 'reasoning', 'planning', 'tool-calling', 'large-context'],
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    supportsStreaming: true,
    supportsToolCalling: true,
  },
  {
    id: 'gpt-4.1-mini',
    provider: 'openai',
    modelName: 'gpt-4.1-mini',
    capabilities: ['fast', 'summarization', 'tool-calling'],
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    supportsStreaming: true,
    supportsToolCalling: true,
  },
  {
    id: 'gemini-2.5-pro',
    provider: 'google',
    modelName: 'gemini-2.5-pro',
    capabilities: ['coding', 'reasoning', 'planning', 'large-context', 'tool-calling'],
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    supportsStreaming: true,
    supportsToolCalling: true,
  },
  {
    id: 'gemini-2.5-flash',
    provider: 'google',
    modelName: 'gemini-2.5-flash',
    capabilities: ['fast', 'summarization', 'large-context', 'tool-calling'],
    contextWindow: 1_048_576,
    maxOutputTokens: 65_536,
    supportsStreaming: true,
    supportsToolCalling: true,
  },
];
